### ISSUE TITLE
Use rollup for UMD build

### ISSUE THREAD

**Issue by aweary** [FormidableLabs/react-progressive-image#14]
Rollup for libraries, webpack for apps.

**Comment by brybrophy** [comment]
@boygirl Do you see a need for this one? I think Rollup does output a smaller/more optimized bundle for libraries compared to Webpack, but this component is so small that I'm not sure how much gain we would really see. Webpack has also come a long way since last December. Finally, I haven't seen Rollup being used in any other Formidable projects I have worked on.

Yea or nay? If nay, I think we could close this one.

**Comment by boygirl** [comment]
I vote nay. I'll close this issue.

**Comment by brybrophy** [comment]
Good call.
